#!/bin/bash
i3status -c ~/.config/i3status/config | while :
do
    read line
    SONG="`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | sed -n '/title/{n;p}' | cut -d '"' -f 2`"
    echo "♬♬ $SONG ♬♬ | $line" || exit 1
done
